"""Scene dict -> generatedScene.h.

Emits the scene declaration and nothing else. Everything with behaviour in it is
in cpp/UsableFunctions.cpp, which compiles unchanged for every scene -- generated
code cannot be reviewed in a diff or stepped through in a debugger, so there is
as little of it as possible: a count, an array, and a list of maker calls.

No numbers appear in the output. Every value is read from the p[] buffer at call
time, which is what lets a parameter change skip the compiler entirely.
"""

from .scene import MAKER, NPARAM

# an object whose maker divides by zero produces NaN rather than crashing, and a
# NaN hitTime loses every comparison against MAGIC_NO_COLLISION -- reading as an
# object that is simply never hit. a scene quietly missing a wall is far worse
# than an exception, so each one is checked before it is built
GUARD = {
    "line":        "if (p[{o}] == 0.0 && p[{o}+1] == 0.0) return {k}+1;",
    "lineSegment": "if (p[{o}] == p[{o}+2] && p[{o}+1] == p[{o}+3]) return {k}+1;",
    "elipse":      "if (p[{o}+2] == 0.0 || p[{o}+3] == 0.0) return {k}+1;",
    "elipseArc":   "if (p[{o}+2] == 0.0 || p[{o}+3] == 0.0) return {k}+1;",
    "portal":      "if ((p[{o}] == p[{o}+2] && p[{o}+1] == p[{o}+3]) ||\n"
                   "        (p[{o}+4] == p[{o}+6] && p[{o}+5] == p[{o}+7])) return {k}+1;",
}

HEADER = """\
// generated by hpcBilliards/codegen.py -- do not edit.
// {n} objects: {summary}
#pragma once
#include "geometry.h"

#ifdef _OPENMP
#pragma omp declare target
#endif
constexpr int nObj = {n};
inline Object objs[nObj];
#ifdef _OPENMP
#pragma omp end declare target
#endif

// p holds every object's parameters end to end; off[k] is where object k's
// begin. returns 0, or 1 + the index of the first object that is degenerate
extern "C" int abBuildScene(const double *p, const int *off) {{
{guards}

{builds}
#ifdef _OPENMP
#pragma omp target update to(objs)
#endif
    return 0;
}}
"""


def _build(k, kind):
    o = f"off[{k}]"
    if kind == "portal":
        # the exit is read for its endpoints and then discarded: asPortal keeps
        # the derived frame in q[], so a one-way portal costs one object and
        # leaves nothing for a particle to bounce off on the far side
        return (f"    {{\n"
                f"        Object entry = makeLineSegment(p[{o}], p[{o}+1], p[{o}+2], p[{o}+3]);\n"
                f"        Object exit  = makeLineSegment(p[{o}+4], p[{o}+5], p[{o}+6], p[{o}+7]);\n"
                f"        objs[{k}] = asPortal(entry, exit, p[{o}+8], p[{o}+9]);\n"
                f"    }}")
    args = ", ".join(f"p[{o}+{j}]" if j else f"p[{o}]" for j in range(NPARAM[kind]))
    return f"    objs[{k}] = {MAKER[kind]}({args});"


def generate(types):
    guards = "\n".join(
        "    " + GUARD[kind].format(o=f"off[{k}]", k=k) for k, kind in enumerate(types))
    builds = "\n".join(_build(k, kind) for k, kind in enumerate(types))
    summary = ", ".join(f"{i}:{t}" for i, t in enumerate(types))
    return HEADER.format(n=len(types), summary=summary, guards=guards, builds=builds)
